[workspace]
resolver = "2"
members = [
  "crates/build-deps",
  "crates/core",
  "crates/cadmus",
  "crates/fetcher",
  "crates/importer",
  "crates/macros",
  "xtask",
]

[workspace.dependencies]
async-trait = "0.1"
blake3 = "1"
cc = "1"
io_tee = "0.1"
bytes = "1"
http = "1"
http-body-util = "0.1"
octocrab = { version = "0.54.2", default-features = false, features = [
    "jwt-rust-crypto",
] }
reqwest-middleware = { version = "0.5.2", default-features = false, features = [
    "form",
    "json",
] }
reqwest-retry = { version = "0.9.1", default-features = false }
reqwest-tracing = { version = "0.7.1", default-features = false }
tower = { version = "0.5", default-features = false }
rust-embed = "8"
rustls = { version = "0.23", default-features = false, features = [
  "ring",
  "logging",
  "std",
  "tls12",
] }
sdl3 = { version = "0.20.0", features = ["use-pkg-config"] }
serde_json = "1.0.149"
tokio-util = { version = "0.7", default-features = false, features = ["rt"] }

[workspace.lints]
rustdoc.private_intra_doc_links = "allow"

[workspace.lints.clippy]
await_holding_lock = "deny"
await_holding_refcell_ref = "deny"

[profile.release-minsized]
inherits = "release"
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true
strip = true
