import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..", "..");
const poDir = join(repoRoot, "docs", "po");
const outputFile = join(__dirname, "..", "i18n", "locales.generated.ts");

/** Locale codes from `docs/po/*.po`, always including English. */
function scanWebsiteLocales() {
  const codes = new Set(["en"]);

  if (existsSync(poDir)) {
    for (const file of readdirSync(poDir)) {
      if (file.endsWith(".po")) {
        codes.add(file.replace(/\.po$/, ""));
      }
    }
  }

  return [...codes].sort((a, b) => a.localeCompare(b));
}

const locales = scanWebsiteLocales();
const displayNames = new Intl.DisplayNames(["en"], { type: "language" });
const labels = Object.fromEntries(
  locales.map((code) => [code, displayNames.of(code) ?? code]),
);

const content = `// This file is auto-generated by scripts/generate-locales.mjs. Do not edit.

export const locales = ${JSON.stringify(locales)} as const;

export type Locale = (typeof locales)[number];

export const localeLabels: Record<Locale, string> = ${JSON.stringify(labels, null, 2)};

export const defaultLocale = "en" as const satisfies Locale;
`;

mkdirSync(dirname(outputFile), { recursive: true });
writeFileSync(outputFile, content);

console.log(`Generated ${locales.length} locale(s): ${locales.join(", ")}`);
