[book]
title = "Cadmus Documentation"
language = "en"

[build]
build-dir = "book"
create-missing = true
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.mermaid-png]
command = "python3 mdbook-mermaid-preprocessor.py"
renderer = ["epub"]

[output.epub]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js", "lang-picker.js"]
additional-css = ["custom.css"]
